version: '3.1'

services:

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - ./data:/mnt/data  

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - postgres

networks:
  postgres:
    driver: bridge